stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - data/raw
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    - feature_engineering.model_type
    outs:
    - data/processed
    - models/vectorizer.pkl

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed
    - models/vectorizer.pkl
    - src/models/model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    - model_building.max_depth
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/models/evaluate.py
    deps:
    - models/model.pkl
    - src/models/evaluate.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/model_info.json
  model_registration:

    cmd: python src/models/register_model.py
    deps:
    - models/model.pkl
    - src/models/register_model.py

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
